version: '3'
services:
  server:
    build:
      context: server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/home/server
    ports:
      - 3000:3000
    command: yarn start-dev
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
  client:
    build:
      context: client
      dockerfile: dev.Dockerfile
    volumes:
      - ./client:/home/client
    ports:
      - 3001:3000
    command: yarn start
    environment:
      NODE_ENV: development
  storybook:
    build:
      context: client
      dockerfile: dev.Dockerfile
    volumes:
      - ./client:/home/client
    ports:
      - 9009:9009
    command: yarn storybook --ci
    environment:
      NODE_ENV: development